config/routes.rb
Rails.application.routes.draw do
  get 'search/', to: "search#index"
  resources :posts
  get 'home/', to:"pages#home"
  get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true

    paginates_per 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.page params[:page]

  end

    
  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @q = Post.ransack(params[:q])
    @posts= @q.result(distinct: true)
 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render '/pages/navbar'%>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "BoutiqueWii", root_path, class:"navbar-brand fs-1 "%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <%= link_to "Inicio", root_path, class:"nav-link active fw-light"%>
        </li>
        <li class="nav-item">
          <%= link_to "Nosotros", '/pages/about', class:"nav-link active fw-light"%>
        </li>
                <li class="nav-item">
          <%= link_to "Productos", '/posts', class:"nav-link active fw-light"%>
        </li>
      </ul>
      <div>
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </div>
      <form class="d-flex" role="search">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
      </form>
      <div class="navbar-nav me-auto mb-2">
        <%= link_to "Buscar", search_path %>
      </div>
    </div>
  </div>
</nav>

app/views/pages/about.html.erb
<div class="container">
    <br>
    <h1>BoutiqueWii</h1>
    <br>
    <p>Somos una pyme dedicada a ofrecer lo que buscas <br> en moda, calidad y precio</p>

    <%= link_to "Inicio", home_path%>

</div>

app/views/pages/home.html.erb
<br>
<div class="container">
    <h1>Boutique Wii</h1>
    <p>Todo para tu comodidad</p>

    <%= link_to "Conocenos", '/pages/about',class:"btn btn-secondary" %>
    <%= link_to "Productos", 'posts',class:"btn btn-primary" %>

</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
 
  <h2>  <%= post.title %></h2>
  <div>
    <%= post.body %>
  </div>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="posts" class="container">

  <h1>Productos</h1>
   
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Ver", post %>
    </p>
  <% end %>
  
  <%= link_to "Agregar producto", new_post_path %>
  
</div>

<div id="posts" class="container">
  <%= paginate @posts%>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/search/_search.html.erb
<br>
<div class="container form-group">
    <%= search_form_for @q, url:"/search", method: :get, class:'d-flex' do |f| %>       
        <%= f.search_field :body_i_cont_any, placeholder: "Descripcion...", class:"form-control me-2" %>
        <%= f.submit "Buscar!", class:"btn btn-outline-success" %>
    <% end %>
</div>
<br>

app/views/search/index.html.erb
<h1 Class="text-center"> <%= pluralize(@posts.count,'resultados')%></h1>

 
 
<%=render 'search/search'%>

<div class="container">
    <table class="table table-dark bg-dark table-striped">
        <thead>
            <tr>
                <th><%=sort_link(@q,:title,"Nombre", default_order: :asc) %></th>
                <th><%=sort_link(@q, :body,"Descripción") %></th>
                <th><%=sort_link(@q, :prize, "Precio") %></th>
                <th><%=sort_link(@q, :size, "Talla") %></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
          <% @posts.each do |post|%>
            <tr>
               <th><%=link_to post.title, post%></th>
               <th><%=link_to post.body, post %></th>
               <th><%=link_to post.price, post%></th>
               <th><%=link_to post.size, post%></th>
               <th><%=link_to "Ver", post%></th>
            </tr>
          <%end%>
        </tbody>
 </div>


 